# Generated by Django 5.1.4 on 2025-06-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=10)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('banner_img_url', models.CharField(max_length=500)),
                ('poster_img_url', models.CharField(blank=True, max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('on_going', 'On Going'), ('completed', 'Completed')], default='on_going', max_length=10)),
                ('age_rank', models.CharField(default='all', max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('native_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='film.content')),
                ('total_seasons', models.PositiveIntegerField(default=1)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.nation')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='film.studio'),
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='film.content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='film.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='film.content')),
                ('intro_duration', models.FloatField(default=0)),
                ('start_intro_time', models.FloatField(default=0)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('video', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('season_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('banner_img_url', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('on_going', 'On Going'), ('completed', 'Completed')], default='on_going', max_length=10)),
                ('num_episodes', models.PositiveIntegerField(default=0)),
                ('age_rank', models.CharField(default='all', max_length=10)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='film.series')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genres', to='film.content')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='film.genre')),
            ],
            options={
                'unique_together': {('content', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='ContentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(choices=[('audio', 'Audio'), ('subtitle', 'Subtitle')], max_length=10)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_languages', to='film.content')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='film.language')),
            ],
            options={
                'unique_together': {('content', 'language', 'language_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentNation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_nations', to='film.content')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='film.nation')),
            ],
            options={
                'unique_together': {('content', 'nation')},
            },
        ),
        migrations.CreateModel(
            name='ContentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('voice_actor', 'Voice Actor'), ('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer'), ('screenwriter', 'Screenwriter'), ('animator', 'Animator'), ('character_designer', 'Character Designer'), ('music_composer', 'Music Composer'), ('sound_director', 'Sound Director'), ('art_director', 'Art Director'), ('executive_producer', 'Executive Producer'), ('original_creator', 'Original Creator'), ('screenplay', 'Screenplay'), ('series_composition', 'Series Composition')], max_length=30)),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_crew', to='film.content')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='film.person')),
            ],
            options={
                'ordering': ['order', 'role'],
                'unique_together': {('content', 'person', 'role', 'character_name')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('intro_duration', models.FloatField(default=0)),
                ('start_intro_time', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('banner_img_url', models.CharField(max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('video', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='film.season')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('season', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='film_conten_content_1f8026_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status'], name='film_conten_status_aba753_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['rating'], name='film_conten_rating_a1d1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-views'], name='film_conten_views_cef0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug'], name='film_conten_slug_059f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contenttag',
            unique_together={('content', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'order')},
        ),
    ]
