# Generated by Django 5.1.4 on 2025-06-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=255)),
                ('watch_duration', models.PositiveIntegerField(default=0, help_text='Watch duration in seconds')),
                ('view_counted', models.BooleanField(default=False, help_text='Whether view has been counted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.content')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.episode')),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='film_viewse_session_de087c_idx'), models.Index(fields=['view_counted'], name='film_viewse_view_co_2ac8e6_idx')],
                'unique_together': {('session_id', 'content', 'episode')},
            },
        ),
    ]
