# Generated by Django 5.1.4 on 2025-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video_path', models.CharField(blank=True, help_text='Path to original video file', max_length=255)),
                ('hls_path', models.CharField(blank=True, help_text='Path to file M3U8', max_length=255)),
            ],
        ),
    ]
